### PR TITLE
Prevent close link

### PR DESCRIPTION
**Pull request by brettz9**
Adds a mechanism to prevent the addition of a close link. Let me know if you want a PR against your current master rather than against my other PRs.

### CODE REVIEW

**Comment by okcoker** [comment]
@brettz9 it is very hard to see whats going on here. Also what is your use case for `preventCloseLink`? As mentioned [here](https://github.com/okcoker/taggle.js/pull/21#issuecomment-149400958) maybe the `onBeforeAddTag`/`onBeforeRemoveTag` can serve your use case? If not, just open another PR with just this extra option added, sans formatting changes and we can re-evaluate.

**Comment by brettz9** [comment]
This is a cumulative PR based on top of my previous jslint one as well as inclusion of rictorres' remove all tags commits. I happened to need the ability to remove all tags and then add them back but without close links.

My use case is is to display the tags based on key modifier input (as per [this repo](https://github.com/brettz9/key-selector) ([demo](https://rawgit.com/brettz9/key-selector/taggle/KeySelector.html)).  I would like the list of modifier keys to display as tags.

**Comment by brettz9** [comment]
And my reason for the key selector would be for allowing the user to save a hot-key combination in preferences for use by web-apps (and possibly browser add-ons).

**Comment by okcoker** [comment]
I'm not completely against the `preventCloseLink` option concept but it just seems pretty specific to your use case. Also, I think I would rather have it called `displayCloseLink`. Does the `getAllTagValues()` function not suffice for what you're trying to do? I guess I'd almost expect you to just use those values returned by that function to create whatever display you want.

Also as far as the PR, I've merged rictorres' commits as well as some other PRs but I'd prefer not to add the formatting changes as I'm incorporating eslint now and will restructure the library a little bit.

**Comment by brettz9** [comment]
Well, besides the close buttons, I like that your library handles that display for me. I'm not much of a CSS guy.  ESLint does look like the way to go with its comprehensively pluggable approach, though I sure wish someone would make a Notepad++ plugin to use it.

**Comment by okcoker** [comment]
Hmmm now that I think about it, maybe it makes more sense to have a `editTag` function that allows you to edit actual tag list item before it's created and added to the textarea. You would provide the function as an option and have it return the `li`. That would allow greater extensibility and we can just have the default value be a function that returns the current close button.

What do you think @brettz9?

**Comment by brettz9** [comment]
That sounds fine by me, thanks!

**Pull request closed without merging**
