### PR TITLE
Prevent ENTER from triggering click events

### PR DESCRIPTION
**Pull request by mic4ael**
Fixes https://github.com/okcoker/taggle.js/issues/49

### CODE REVIEW

**Comment by okcoker** [comment]
Where and when does pressing `enter` make the click event happen?

**Comment by okcoker** [comment]
Should have looked at #49 first :)

**Comment by okcoker** [comment]
Can you add a test to make sure this `type` attribute is there?

**Comment by mic4ael** [comment]
Sure, I am gonna do it right away

**Comment by mic4ael** [comment]
Done, you can have a look right now and let me know if everything looks fine

**Comment by okcoker** [comment]
Thanks @mic4ael!

**Pull request merged**
