### PR TITLE
Add tagLimit to options

### PR DESCRIPTION
**Pull request by spoonben**
Limit the number of tags a user is allowed to add

### CODE REVIEW

**Comment by okcoker** [comment]
Was considering adding this as noted in #39. Can you rename `tagLimit` to `maxTags` as mentioned in that ticket? I noticed most of the options are suffixed with `tags` so I might as well keep that part consistent I suppose :grimacing:

**Comment by spoonben** [comment]
@okcoker no problem, updated.

**Comment by EchelonAgency** [comment]
Hi guys, do you know the best way to prevent the input from appearing if maxTags has been hit? So if maxTags : 3 then after the third tag the input would no longer appear? I was thinking of somehow adding a class in there.

**Comment by okcoker** [comment]
@EchelonAgency you could do something like:
```js
var instance = new Taggle('example1', {
    onTagAdd: function() {
        if (instance.getTagValues().length === 3) {
             // Hide input
        }
    } 
});
```

**Comment by EchelonAgency** [comment]
@okcoker Oh thanks for the quick reply! I still can't target the input which is annoying :s I'll keep trying!

**Comment by okcoker** [comment]
@EchelonAgency [try this](http://jsfiddle.net/okcoker/m6n0z8ww/4/)

**Comment by EchelonAgency** [comment]
That worked perfectly thanks a lot for the effort @okcoker!

**Comment by spoonben** [comment]
@EchelonAgency @okcoker I actually found it more useful to set the input "maxlength" to 0 so that users can still backspace to remove a tag if they want, little more accessible.

**Pull request merged**
