### PR TITLE
Add placeholder for hidden input to emphasize mouse click area

### PR DESCRIPTION
**Pull request by 2korzhik**
In my case it was not so obvious that taggle field is editable. I was asked to place some placeholder at  the end of tag list.

### CODE REVIEW

**Comment by okcoker** [comment]
There is already a [placeholder](https://github.com/okcoker/taggle.js/pull/20/files#diff-e113ff04b2bf8f68fa28e11be484f9deR67) option right above this.

**Comment by 2korzhik** [comment]
Those are two different placeholders and they act different.

**Comment by okcoker** [comment]
Right, but you've [commented out](https://github.com/okcoker/taggle.js/pull/20/files#diff-e113ff04b2bf8f68fa28e11be484f9deR338) a core piece of functionality. The `placeholder` option already in place adds a fake placeholder on top of your textarea and should emphasize the same mouse click area you're trying to achieve with `inputPlaceholder`.

The difference being that the `placeholder` option already in place is easier to style via css.

**Comment by 2korzhik** [comment]
Yes, you're right.

**Pull request closed without merging**
